name: open github issue

on:
  push:
    branches:
      - 'master'

jobs:
  open-issue:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: lint
        run: yarn run lint
